#!/bin/bash

# Quote and Eventlog validating Attestation Server.
#
# This server accepts incoming HTTP POST requests from an attesting machine
# that contain a tar file of a TPM Endorsement Key, Attestation Key, Quote,
# PCR list, Eventlog and other details. It performs three actions:
#
# * Validates that the Quote is signed by the AK
# * Validates that the EK certificate has a good trust chain
# * Validates that the PCR extensions in the Eventlog produce the PCRs in the quote
#
# It then invokes an external handler to verify that the eventlog
# meets the policy requirements, and will return any output from this
# handler to the attesting machine.

PORT=8080
if [[ $# -gt 0 ]]; then
	if [[ $# -gt 1 ]]; then
		echo "Usage: attest-server [port]" >&2
		exit 1
	fi
	PORT=$1
fi

export FLASK_APP=sbin/attest_server_sub
flask run --host=0.0.0.0 --port=$PORT
